# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.3.3-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: social_stream-base-{{ checksum "./base/Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
             cd ./base/spec/dummy && bundle update

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: social_stream-base-{{ checksum "./base/Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run:   cd ./base/spec/dummy  && bundle exec rake db:create
      - run:   cd ./base/spec/dummy  && bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run testsfile:///usr/local/bundle/gems/activesupport-4.0.0/lib/active_support/core_ext/numeric/conversions.rb:131:in%20%60block%20(2%20levels)%20in%20%3Cclass:Numeric%3E'
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

              cd ./base && bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results