source "http://rubygems.org"

gem "rails", "~>4.0.0"
gem "capybara"
gem "sqlite3", '~> 1.3.6'

group :production do
    gem "mysql2"
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails', '~>4.8.2'
end

gem "social_stream-base", path: "../../"

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'
