source "http://rubygems.org"

gem "rails", "~>3.2"
gem "capybara", ">= 0.4.0"
gem "sqlite3"

gem "social_stream-base", path: "../../"
gem "avatars_for_rails", path: "../../../avatars_for_rails"

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'
