source "http://rubygems.org"

# Uncomment the following lines if you are planing to
# use a local code of mailboxer or avatar_for_rails gems
#
# gem 'mailboxer', :path => '../mailboxer'
# gem 'social_cheesecake', :path => '../../SocialCheesecake/social_cheesecake'


gemspec

group :production do
    gem "mysql2"
end

gem 'avatars_for_rails', :github => 'kainio/avatars_for_rails'
