source "http://rubygems.org"

# Uncomment the following lines if you are planing to
# use a local code of mailboxer or avatar_for_rails gems
#
# gem 'mailboxer', :path => '../mailboxer'
# gem 'social_cheesecake', :path => '../../SocialCheesecake/social_cheesecake'


gemspec

gem 'avatars_for_rails', :path => '../avatars_for_rails'
